# Generated by Django 5.2.5 on 2025-09-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registration_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='TBD', help_text="Enter the physical address or 'Online'", max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Organizer', 'Event Organizer'), ('Participant', 'Participant')], max_length=15),
        ),
    ]
