# Generated by Django 5.2.5 on 2025-09-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_location_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
