# Generated by Django 5.2.5 on 2025-09-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='feedback_request_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
