# Generated by Django 5.2.5 on 2025-09-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_registration_feedback_request_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
