# Generated by Django 5.2.5 on 2025-09-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_registration_attended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited seats.', null=True),
        ),
    ]
