# Generated by Django 5.2.5 on 2025-10-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
