# Generated by Django 5.2.5 on 2025-10-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_online',
        ),
        migrations.AddField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('In-Person', 'In-Person Only'), ('Online', 'Online Only'), ('Hybrid', 'Hybrid (In-Person and Online)')], default='In-Person', max_length=10),
        ),
    ]
