# Generated by Django 5.2.5 on 2025-10-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_is_online_event_event_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_fee',
            field=models.CharField(choices=[('Free', 'Free Entry'), ('Paid', 'Paid Entry')], default='Free', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Physical address or room number for the event.', max_length=255, null=True),
        ),
    ]

