# Generated by Django 5.2.5 on 2025-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_entry_fee_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the fee amount if this is a paid event.', max_digits=8, null=True),
        ),
    ]
