# Generated by Django 5.2.5 on 2025-10-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget for the event.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Assigned by HOD upon approval.', max_length=255, null=True),
        ),
    ]
