# Generated by Django 5.2.5 on 2025-10-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
